### ISSUE TITLE
HTTP ERROR 503

### ISSUE THREAD

**Issue by bksmile** [QIWI-API/bill-payments-docs#10]
https://edge.qiwi.com/checkout/invoice/pay/wallet

not working "HTTP ERROR 503"
![image](https://user-images.githubusercontent.com/29016651/82718846-b391ef80-9c94-11ea-81fe-2553accd7efe.png)

**Comment by Khromushkin** [comment]
Thank you for this bugreport. We fixed the problem.
/checkout/ endpoint is deprecated. We will fix the docs' occurences of it, replacing with /checkout-api/. 
Consider using /checkout-api/ instead.
