### ISSUE TITLE
[Предложение] themeCode

### ISSUE THREAD

**Issue by candro** [QIWI-API/bill-payments-docs#8]
Приветствую разработчиков и писателей доков для киви. Может быть стоит уделить какое-то время для вынесения **themeCode** сюда https://edge.qiwi.com/widgets-api/api/p2p/protected/personal-data, https://edge.qiwi.com/checkout-api/users/me или в другой новый метод?

Получение **themeCode** через https://edge.qiwi.com/widgets-api/api/p2p/protected/generate-public-key костыльный костыль. Почините кто-нибдуь пожалуйста. Спасибо!

**Comment by candro** [comment]
Вы это сами делаете на сайте https://qiwi.com/p2p-admin/transfers/link. Понятно, что это еще в бете можно сказать, но кто-то из штата разрабов может это пофиксить.

**Comment by Khromushkin** [comment]
Приветствую и спасибо за предложение!

Запрос generate-public-key организует работу пользователя обычного кошелька как p2p мерчанта. Запрос идемпотентен и используется для создания и получения данных для работы p2p мерчанта, в том числе themeCode.

В будущем мы планируем проводить бизнес-логику по организации работы p2p мерчанта в оффлайне, и тогда мы сможем предоставить данные о мерчанте по get запросу, аналогично /users/me или /personal-data , но скорее всего это не будет расширением конкретно одного из этих двух запросов.
